### ISSUE TITLE
lmao kids

### ISSUE THREAD

**Issue by sohamsuvarna** [NextGenOrg/Swiftcord#3]
lmao

**Comment by abh80** [comment]
Yes kid rather than showing your noob skills in editing issues do what being said above. Also if you don't know how to delete package here is an example hopes it helps you 😄 
```bash
npm unpublish swiftcord --force
```

**Comment by shadeoxide** [comment]
or just mail npm to delete your package lol

**Comment by sohamsuvarna** [comment]
aight I close this
